### ISSUE TITLE
Integration with home assistant

### ISSUE THREAD

**Issue by drgreenbaum** [Phype/purei9-cli#2]
Great work! Been waiting for this a long time. Their integration with IFTTT has been failing for a long time. Is it possible to integrate your code with home assistant or MQTT so that the robot can be used with the Vacuum template: https://www.home-assistant.io/integrations/vacuum.template/ ?

**Comment by Phype** [comment]
Well, it's possible, but writing a home assistant addon seems not that straightforward tbh. When i look at this [code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/vacuum.py) i only find layers upon layers of abstractions, but nowhere seems to be code which controls how the connection to the robot is made and how the protocol looks like.

Maybe home assistant allows you to create a simple plugin which just work by calling a command line program or something like that? Then you can just point it to the purei9-cli program and set some parameters.

**Comment by Phype** [comment]
Ah i see. So home assistant seems to be built mostly on third party libs (like [this one](https://github.com/rytilahti/python-miio/)). Maybe you can create an issue there and ask if they can build in integration based on my code?

**Comment by MartinWilden** [comment]
I am also looking for a Home Assistant Integration. The simplest integration seems to be the template (https://www.home-assistant.io/integrations/vacuum.template/) 

_The template platform creates vacuums that combine integrations and provides the ability to **run scripts or invoke services** for each of the start, pause, stop, return_to_base, clean_spot, locate and set_fan_speed commands of a vacuum._

Alternatively would be nevertheless also over MQTT (https://www.home-assistant.io/integrations/vacuum.mqtt/) a good and lasting, although probably more complicated way

**Comment by Phype** [comment]
I think you could hack something together by creating a shell command service (https://www.home-assistant.io/integrations/shell_command/) and then invoking this service via the vacuum template. I don't know or have a Home Assistant Installation, so i cannot test. Still, i think the proper way of doing this would be to create a `integration` like the ones in here:
https://github.com/home-assistant/core/tree/dev/homeassistant/components

**Comment by drgreenbaum** [comment]
Seems like a good place to start! Does the robot push out data or do you have to poll state changes every x seconds?

**Comment by Phype** [comment]
You have to poll. Even if the TCP connection is left open, its a query/response protocol, the robot won't send anything without a request.

**Comment by Phype** [comment]
Home assistant integration is available here: https://github.com/anhaehne/homeassistant_electrolux_purei9 based on code from this repository
